/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication3;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


/**
 *
 * @author shammaaas
 *
 */
public class BankViewerFrame extends javax.swing.JFrame {

    ButtonGroup radioBtnsGroup = new ButtonGroup();
    ExamManager examManager;
    String course;
    public BankViewerFrame() {
     initComponents();
        this.setTitle(course+" Questions Bank");// muntaha added from nife
        this.course = course;
        examManager = new ExamManager(course);
        radioBtnsGroup.add(mcQ);
        radioBtnsGroup.add(tf);
        radioBtnsGroup.add(fb);
        choicesPanel.setVisible(false);
        
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                int answers = JOptionPane.showConfirmDialog(null, "Do you want to save the applied changes?", "Alert!", JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE);
                
                if (answers == JOptionPane.YES_OPTION) {
                    
                    try {
                        
                        examManager.exportQBank();
                        JOptionPane.showMessageDialog(null, "Thank you for using the Exam Manager\nAll Questions have been saved", "Message", JOptionPane.INFORMATION_MESSAGE);
                        
                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(null, "Error during saving the data", "Exam Manager", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    
                    JOptionPane.showMessageDialog(null, "Thank you for using the Exam Manager", "Message", JOptionPane.INFORMATION_MESSAGE);
                }
                
                System.exit(0);
                
            }
        }
        );
    }
    
    
    
    public BankViewerFrame(String course) {
        initComponents();
        this.setTitle(course+" Questions Bank");// muntaha added from nife
        this.course = course;
        examManager = new ExamManager(course);
        radioBtnsGroup.add(mcQ);
        radioBtnsGroup.add(tf);
        radioBtnsGroup.add(fb);
        choicesPanel.setVisible(false);
        
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                int answers = JOptionPane.showConfirmDialog(null, "Do you want to save the applied changes?", "Alert!", JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE);
                
                if (answers == JOptionPane.YES_OPTION) {
                    
                    try {
                        
                        examManager.exportQBank();
                        JOptionPane.showMessageDialog(null, "Thank you for using the Exam Manager\nAll Questions have been saved", "Message", JOptionPane.INFORMATION_MESSAGE);
                        
                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(null, "Error during saving the data", "Exam Manager", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    
                    JOptionPane.showMessageDialog(null, "Thank you for using the Exam Manager", "Message", JOptionPane.INFORMATION_MESSAGE);
                }
                
                System.exit(0);
                
            }
        }
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        gradestext = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        qtext = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        idtext = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fb = new javax.swing.JRadioButton();
        mcQ = new javax.swing.JRadioButton();
        tf = new javax.swing.JRadioButton();
        answerText = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();
        choicesPanel = new javax.swing.JPanel();
        choiceTwoTxtf = new javax.swing.JTextField();
        choiceOneTxtf = new javax.swing.JTextField();
        choiceThreeTxtf = new javax.swing.JTextField();
        choiceFourTxtf = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextArea1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        header = new javax.swing.JTextField();
        nOq = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        withAnswers = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        chName = new javax.swing.JTextField();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Question Bank");
        setPreferredSize(new java.awt.Dimension(900, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add a New Questions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 18))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setText("Choose the type of the Qustion:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 270, 30));

        gradestext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradestextActionPerformed(evt);
            }
        });
        jPanel2.add(gradestext, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 190, 30));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setText("Question Text");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 110, 30));

        qtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtextActionPerformed(evt);
            }
        });
        jPanel2.add(qtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 190, 30));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel3.setText("Question ID");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 100, 30));

        idtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idtextActionPerformed(evt);
            }
        });
        jPanel2.add(idtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 190, 30));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel4.setText("Correct Answer");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 120, 30));

        fb.setText("Fill Blank ");
        fb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fbActionPerformed(evt);
            }
        });
        jPanel2.add(fb, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));

        mcQ.setText("MCQ");
        mcQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcQActionPerformed(evt);
            }
        });
        jPanel2.add(mcQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        tf.setText("True/False");
        tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfActionPerformed(evt);
            }
        });
        jPanel2.add(tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        answerText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerTextActionPerformed(evt);
            }
        });
        jPanel2.add(answerText, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 140, 30));

        jToggleButton1.setText("Add Question");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 130, 40));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel7.setText("Possible Grades");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 120, 30));

        choicesPanel.setBackground(new java.awt.Color(255, 255, 255));
        choicesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Answers for MCQ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP));
        choicesPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        choiceTwoTxtf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        choicesPanel.add(choiceTwoTxtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 120, 30));

        choiceOneTxtf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        choicesPanel.add(choiceOneTxtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 120, 30));

        choiceThreeTxtf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        choiceThreeTxtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choiceThreeTxtfActionPerformed(evt);
            }
        });
        choicesPanel.add(choiceThreeTxtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 140, 30));

        choiceFourTxtf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        choicesPanel.add(choiceFourTxtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 140, 30));

        jLabel19.setText("4");
        choicesPanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 20, 20));

        jLabel20.setText("1");
        choicesPanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 20, 30));

        jLabel21.setText("2");
        choicesPanel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 20, 30));

        jLabel22.setText("3");
        choicesPanel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 20, 20));

        jPanel2.add(choicesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 360, 110));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 380, 440));

        jTextArea1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Generate Exam", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 18))); // NOI18N
        jTextArea1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel6.setText("Chapter Name");
        jTextArea1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 120, 30));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel8.setText("Exam Header");
        jTextArea1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 120, 30));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel9.setText("Number of Questions");
        jTextArea1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 160, 30));

        header.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                headerActionPerformed(evt);
            }
        });
        jTextArea1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 190, 30));

        nOq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nOqActionPerformed(evt);
            }
        });
        jTextArea1.add(nOq, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 190, 30));

        jButton1.setText("Generet Exam");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jTextArea1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, -1));

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jTextArea1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 190, 30));

        withAnswers.setText("With Answers");
        withAnswers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withAnswersActionPerformed(evt);
            }
        });
        jTextArea1.add(withAnswers, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, -1));

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane1.setViewportView(jTextArea3);

        jTextArea1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        getContentPane().add(jTextArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 430, 270));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Delete Chapter Questions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 18))); // NOI18N
        jPanel3.setToolTipText("");
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel10.setText("Chapter Name");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 120, 30));

        chName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chNameActionPerformed(evt);
            }
        });
        jPanel3.add(chName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 190, 30));

        jToggleButton2.setText("Add Question");
        jPanel3.add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 150, 40));

        jToggleButton3.setText("Add Question");
        jPanel3.add(jToggleButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 150, 40));

        jToggleButton4.setText("Remove");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 100, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 420, 130));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gradestextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradestextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gradestextActionPerformed

    private void qtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtextActionPerformed

    private void idtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idtextActionPerformed

    private void fbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fbActionPerformed
        choicesPanel.setVisible(false);
    }//GEN-LAST:event_fbActionPerformed

    private void mcQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcQActionPerformed
        choicesPanel.setVisible(true);
    }//GEN-LAST:event_mcQActionPerformed

    private void tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfActionPerformed
        choicesPanel.setVisible(false);
    }//GEN-LAST:event_tfActionPerformed

    private void answerTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answerTextActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        if (!validateOfField(qtext, "Question Text")) {
            return;
        }
        
        if (!validateOfField(idtext, "Question ID")) {
            return;
        }
        
        if (!validateOfField(gradestext, "Question Possible Grade")) {
            return;
        }
        
        if (!validationOfNumber(gradestext, "Question Possible Grade")) {
            
            return;
            
        }
        
        if (!(mcQ.isSelected() || tf.isSelected() || fb.isSelected())) {
            
            JOptionPane.showMessageDialog(this, "Question type field is required.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!validateOfField(answerText, "Question Correct Answer")) {
            return;
        }
        
        if (mcQ.isSelected()) {
            
            if (!validateOfField(choiceOneTxtf, "First Choice")) {
                return;
            }
            
            if (!validateOfField(choiceTwoTxtf, "Second Choice")) {
                return;
            }
            
            if (!validateOfField(choiceThreeTxtf, "Third Choice")) {
                return;
            }
            
            if (!validateOfField(choiceFourTxtf, "Fourth Choice")) {
                return;
            }

            /*Validate the correct answer --> should be integer [0-3] */
            if (!validationOfNumber(answerText, "Question Correct Answer")) {
                
                return;
                
            }
            
            int correctAnswerIndex = Integer.parseInt(answerText.getText());
            
            if (correctAnswerIndex < 0 || correctAnswerIndex > 3) {
                JOptionPane.showMessageDialog(this, "Answer for MCQ should be a number >=0 and < 3", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
        }
        
        if (tf.isSelected()) {
            
            if (!(answerText.getText().trim().equals("true") || answerText.getText().trim().equals("false"))) {
                JOptionPane.showMessageDialog(this, "Answer should be 'true' or 'false' only", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
        }

        /* All fields are validated now , so get values */
        String qText = qtext.getText().trim();
        String qID = idtext.getText().trim();
        double grade = Double.parseDouble(gradestext.getText().trim());
        
        boolean Added;
        
        if (mcQ.isSelected()) {
            
            String[] choices = {
                choiceOneTxtf.getText().trim(),
                choiceTwoTxtf.getText().trim(),
                choiceThreeTxtf.getText().trim(),
                choiceFourTxtf.getText().trim()};
            int correctAnswerIndex = Integer.parseInt(answerText.getText());
            
            Added = examManager.addNewQuestion(new MCQ(qText, qID, grade, correctAnswerIndex, choices));
            
        } else if (tf.isSelected()) {
            
            boolean answer = Boolean.parseBoolean(answerText.getText().trim());
            Added = examManager.addNewQuestion(new TrueFalseQ(qText, qID, grade, answer));
            
        } else {
            System.out.println("random");
            Added = examManager.addNewQuestion(new FillBlankQ(qText, qID, grade, answerText.getText().trim()));
            System.out.println(Added);
        }
        
        if (Added) {
            JOptionPane.showMessageDialog(this, "New question has been added successfully !", "Add Question", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Addition Wasn't Succesful!.", "Add Question", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void choiceThreeTxtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choiceThreeTxtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_choiceThreeTxtfActionPerformed

    private void headerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_headerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_headerActionPerformed

    private void nOqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nOqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nOqActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         if (!validateOfField(header, "Exam Header")) {
            return;
        }
        
        if (!validateOfField(nOq, "Number of Questions")) {
            return;
        }
        
        if (!validationOfNumber(nOq, "Number of Questions")) {
            return;
        }
        
        int numOfQuestions;
        try {
            numOfQuestions = Integer.parseInt(nOq.getText().trim());
            
        } catch (NumberFormatException ex) {
            
            JOptionPane.showMessageDialog(this, "Only Integers are allowed in Number of Questions field !", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        /*Chapter name possaible to have empty value (random questions) */
        boolean withAnswer = withAnswers.isSelected();
        
        try {
            
            examManager.generateExam(header.getText(), numOfQuestions, chName.getText().trim(), withAnswer);

            /*Read the generated exam */
            File file = new File(course + "Exam.txt");
            
            BufferedReader br = new BufferedReader(new FileReader(file));
            jTextArea3.setText("");/*clear the text-area*/
            
            String st;
            while ((st = br.readLine()) != null) {
         jTextArea3.append(st+ "\n");
         
                
            }
            
            JOptionPane.showMessageDialog(this, "Exam has been generated successfully !", "Generate Exam", JOptionPane.INFORMATION_MESSAGE);
            
        } catch (Exception ex) {
            
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            
        }        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void withAnswersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withAnswersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_withAnswersActionPerformed

    private void chNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chNameActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
 if (!validateOfField(chName, "Chapter Name")) {
            return;
        }
        
        examManager.removeChapterQuestions(chName.getText());
        JOptionPane.showMessageDialog(this, chName.getText() + " questions removed successfully !\nMake sure to save your work.", "Questions Removed", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_jToggleButton4ActionPerformed

        public void clearFields() {
        
        qtext.setText("");
        idtext.setText("");
        gradestext.setText("");
        answerText.setText("");
        choiceOneTxtf.setText("");
        choiceTwoTxtf.setText("");
        choiceThreeTxtf.setText("");
        choiceFourTxtf.setText("");
        
        radioBtnsGroup.clearSelection();
    }
     private boolean validateOfField(JTextField fields, String fieldName) {// changed one
        
        if (fields.getText().trim().equals("")) {

            //display an error message
            JOptionPane.showMessageDialog(this, fieldName + " field is required.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
    
    private boolean validationOfNumber(JTextField field, String fieldName) {//changed one
        
        String st = field.getText().trim();

        //  check if it's invalid number
        try {
            
            Double.parseDouble(st);//if it's not a valid number will throw an exception
            return true; //ok 
        } catch (NumberFormatException e) {

            //error message
            JOptionPane.showMessageDialog(this, "Only Numbers are alowed in " + fieldName + " Field.", "Error", JOptionPane.ERROR_MESSAGE);
            
            return false;
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BankViewerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BankViewerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BankViewerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BankViewerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BankViewerFrame(args[0]).setVisible(true);
                
                //new BankViewerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answerText;
    private javax.swing.JTextField chName;
    private javax.swing.JTextField choiceFourTxtf;
    private javax.swing.JTextField choiceOneTxtf;
    private javax.swing.JTextField choiceThreeTxtf;
    private javax.swing.JTextField choiceTwoTxtf;
    private javax.swing.JPanel choicesPanel;
    private javax.swing.JRadioButton fb;
    private javax.swing.JTextField gradestext;
    private javax.swing.JTextField header;
    private javax.swing.JTextField idtext;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jTextArea1;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JRadioButton mcQ;
    private javax.swing.JTextField nOq;
    private javax.swing.JTextField qtext;
    private javax.swing.JRadioButton tf;
    private javax.swing.JCheckBox withAnswers;
    // End of variables declaration//GEN-END:variables
}
